### ISSUE TITLE
Could you write a demo on how to run this model on a TPU?

### ISSUE THREAD

**Issue by fran-babylon** [CyberZHG/keras-gpt-2#5]
**Is your feature request related to a problem? Please describe.**
I've been trying to train/predict with gpt-2 on colab with TPU support, and I've met only hurdles. I see you have a parameter for supporting tpus in the model loader, but colab doesn't like a pure keras model. I've tried to convert it to a tf.keras or a tf estimator, but neither worked for me.

**Comment by CyberZHG** [comment]
See CyberZHG/keras-bert#64.
