### ISSUE TITLE
Incompatible depandence warning using with keras-bert.

### ISSUE THREAD

**Issue by BrikerMan** [CyberZHG/keras-gpt-2#7]
**Describe the Bug**

Pip install will report ERROR while using keras-bert with keras-gpt2.

```
ERROR: keras-gpt-2 0.10.0 has requirement keras-transformer==0.25.0, but you'll have keras-transformer 0.23.0 which is incompatible.
```

**Version Info**

keras-bert==0.57.0
keras-gpt-2==0.10.0

**Comment by CyberZHG** [comment]
Specific versions were removed. Use:

```
keras-bert==0.57.1
keras-gpt-2==0.11.1
```

**Comment by BrikerMan** [comment]
> Specific versions were removed. Use:
> 
> ```
> keras-bert==0.57.1
> keras-gpt-2==0.11.1
> ```

Thanks, man.
