### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by NaxAlpha** [CyberZHG/keras-gpt-2#8]
**Is your feature request related to a problem? Please describe.**
There is no documentation about training.

**Describe the solution you'd like**
A simple script/test or doc to train on my dataset.

**Describe alternatives you've considered**
N/A

**Additional context**
If i know how to train model, I will be able to prepare dataset accordingly.

**Comment by mukatee** [comment]
I see this is closed as stale but would it be possible to add an example of how to fine-tune a pre-trained model loaded from a checkpoint with my own data?

**Comment by BenjaminWegener** [comment]
https://github.com/CyberZHG/keras-gpt-2/pull/13
